echo 40
time ./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 10000
echo 42
time ./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 10000
echo 44
time ./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 10000
echo 46
time ./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 10000

