echo A30
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A32
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A34
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A36
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A38
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A40
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A42
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A44
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A46
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A48
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A50
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A52
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
echo A54
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW W 1000
