echo A40
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A42
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A44
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A46
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A48
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A50
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000
echo A52
./TheSolvers BWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW B 1000

